
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTIPLYDIVIDEASSIGN BOOL COMMA C_CHANNEL DIVIDE ELSE EQ GE GT IDENTIFIER IF INPUT LBRACE LE LPAREN LT MINUS MULTIPLY NE NUMBER OUTPUT PAR PLUS RBRACE RECEIVE RPAREN SEMICOLON SEND SEQ STRING WHILEprograma_minipar : bloco_stmtbloco_stmt : bloco_SEQ\n| bloco_PARbloco_SEQ : SEQ LPAREN stmts RPARENbloco_PAR : PAR LPAREN stmts RPARENstmts : stmt\n| stmt SEMICOLON stmtsstmt : atribuicao\n| if_stmt\n| while_stmt\n| canal_comatribuicao : IDENTIFIER ASSIGN exprif_stmt : IF LPAREN BOOL RPAREN stmt\n| IF LPAREN BOOL RPAREN stmt ELSE stmtwhile_stmt : WHILE LPAREN BOOL RPAREN stmtexpr : termo\n| expr PLUS termo\n| expr MINUS termotermo : fator\n| termo MULTIPLY fator\n| termo DIVIDE fatorfator : IDENTIFIER\n| NUMBERcanal_com : C_CHANNEL IDENTIFIER IDENTIFIER IDENTIFIER'
    
_lr_action_items = {'SEQ':([0,],[5,]),'PAR':([0,],[6,]),'$end':([1,2,3,4,20,26,],[0,-1,-2,-3,-4,-5,]),'LPAREN':([5,6,16,17,],[7,8,23,24,]),'IDENTIFIER':([7,8,18,21,22,25,35,36,37,38,39,40,41,49,],[15,15,25,15,28,35,42,28,28,28,28,15,15,15,]),'IF':([7,8,21,40,41,49,],[16,16,16,16,16,16,]),'WHILE':([7,8,21,40,41,49,],[17,17,17,17,17,17,]),'C_CHANNEL':([7,8,21,40,41,49,],[18,18,18,18,18,18,]),'RPAREN':([9,10,11,12,13,14,19,27,28,29,30,31,32,33,34,42,43,44,45,46,47,48,50,],[20,-6,-8,-9,-10,-11,26,-7,-22,-12,-16,-19,-23,40,41,-24,-17,-18,-20,-21,-13,-15,-14,]),'SEMICOLON':([10,11,12,13,14,28,29,30,31,32,42,43,44,45,46,47,48,50,],[21,-8,-9,-10,-11,-22,-12,-16,-19,-23,-24,-17,-18,-20,-21,-13,-15,-14,]),'ELSE':([11,12,13,14,28,29,30,31,32,42,43,44,45,46,47,48,50,],[-8,-9,-10,-11,-22,-12,-16,-19,-23,-24,-17,-18,-20,-21,49,-15,-14,]),'ASSIGN':([15,],[22,]),'NUMBER':([22,36,37,38,39,],[32,32,32,32,32,]),'BOOL':([23,24,],[33,34,]),'MULTIPLY':([28,30,31,32,43,44,45,46,],[-22,38,-19,-23,38,38,-20,-21,]),'DIVIDE':([28,30,31,32,43,44,45,46,],[-22,39,-19,-23,39,39,-20,-21,]),'PLUS':([28,29,30,31,32,43,44,45,46,],[-22,36,-16,-19,-23,-17,-18,-20,-21,]),'MINUS':([28,29,30,31,32,43,44,45,46,],[-22,37,-16,-19,-23,-17,-18,-20,-21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa_minipar':([0,],[1,]),'bloco_stmt':([0,],[2,]),'bloco_SEQ':([0,],[3,]),'bloco_PAR':([0,],[4,]),'stmts':([7,8,21,],[9,19,27,]),'stmt':([7,8,21,40,41,49,],[10,10,10,47,48,50,]),'atribuicao':([7,8,21,40,41,49,],[11,11,11,11,11,11,]),'if_stmt':([7,8,21,40,41,49,],[12,12,12,12,12,12,]),'while_stmt':([7,8,21,40,41,49,],[13,13,13,13,13,13,]),'canal_com':([7,8,21,40,41,49,],[14,14,14,14,14,14,]),'expr':([22,],[29,]),'termo':([22,36,37,],[30,43,44,]),'fator':([22,36,37,38,39,],[31,31,31,45,46,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa_minipar","S'",1,None,None,None),
  ('programa_minipar -> bloco_stmt','programa_minipar',1,'p_programa_minipar','analisadorSintatico.py',13),
  ('bloco_stmt -> bloco_SEQ','bloco_stmt',1,'p_bloco_stmt','analisadorSintatico.py',17),
  ('bloco_stmt -> bloco_PAR','bloco_stmt',1,'p_bloco_stmt','analisadorSintatico.py',18),
  ('bloco_SEQ -> SEQ LPAREN stmts RPAREN','bloco_SEQ',4,'p_bloco_SEQ','analisadorSintatico.py',22),
  ('bloco_PAR -> PAR LPAREN stmts RPAREN','bloco_PAR',4,'p_bloco_PAR','analisadorSintatico.py',26),
  ('stmts -> stmt','stmts',1,'p_stmts','analisadorSintatico.py',30),
  ('stmts -> stmt SEMICOLON stmts','stmts',3,'p_stmts','analisadorSintatico.py',31),
  ('stmt -> atribuicao','stmt',1,'p_stmt','analisadorSintatico.py',38),
  ('stmt -> if_stmt','stmt',1,'p_stmt','analisadorSintatico.py',39),
  ('stmt -> while_stmt','stmt',1,'p_stmt','analisadorSintatico.py',40),
  ('stmt -> canal_com','stmt',1,'p_stmt','analisadorSintatico.py',41),
  ('atribuicao -> IDENTIFIER ASSIGN expr','atribuicao',3,'p_atribuicao','analisadorSintatico.py',45),
  ('if_stmt -> IF LPAREN BOOL RPAREN stmt','if_stmt',5,'p_if_stmt','analisadorSintatico.py',49),
  ('if_stmt -> IF LPAREN BOOL RPAREN stmt ELSE stmt','if_stmt',7,'p_if_stmt','analisadorSintatico.py',50),
  ('while_stmt -> WHILE LPAREN BOOL RPAREN stmt','while_stmt',5,'p_while_stmt','analisadorSintatico.py',57),
  ('expr -> termo','expr',1,'p_expr','analisadorSintatico.py',61),
  ('expr -> expr PLUS termo','expr',3,'p_expr','analisadorSintatico.py',62),
  ('expr -> expr MINUS termo','expr',3,'p_expr','analisadorSintatico.py',63),
  ('termo -> fator','termo',1,'p_termo','analisadorSintatico.py',70),
  ('termo -> termo MULTIPLY fator','termo',3,'p_termo','analisadorSintatico.py',71),
  ('termo -> termo DIVIDE fator','termo',3,'p_termo','analisadorSintatico.py',72),
  ('fator -> IDENTIFIER','fator',1,'p_fator','analisadorSintatico.py',79),
  ('fator -> NUMBER','fator',1,'p_fator','analisadorSintatico.py',80),
  ('canal_com -> C_CHANNEL IDENTIFIER IDENTIFIER IDENTIFIER','canal_com',4,'p_canal_com','analisadorSintatico.py',84),
]
